language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "iojs"
before_script:
  - npm install -g jasmine-node
  - npm install -g gulp
  - npm install gulp
  - npm install gulp-babel
  - npm install gulp-clean
  - npm install gulp-concat
  - npm install gulp-env
  - npm install gulp-eslint
  - npm install gulp-filesize
  - npm install gulp-mocha
  - npm install gulp-mocha-phantomjs
  - npm install gulp-nodemon
  - npm install gulp-rename
  - npm install gulp-sass
  - npm install gulp-shell
  - npm install gulp-uglify
  - npm install gulp-util
  - npm install webpack-stream
  - echo '{"NODE_ENV":"production"}'> ./server/config/.env.json
  
script: 'gulp test'
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "iojs"
