language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "iojs"
before_script:
  - npm install -g jasmine-node
  - npm install -g gulp
script: 'gulp test'
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "iojs"
