language: node_js
env:
  - NODE_ENV=production
node_js:
  - "6"
  - "5"
  - "4"
  - "iojs"
before_script:
  - npm install -g jasmine-node
  - npm install -g gulp
  - npm install --save-dev gulp
  - npm install -g gulp-babel
script: 'gulp test'
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "iojs"
